export enum BrazilianState {
  AC = 'AC',
  AL = 'AL',
  AM = 'AM',
  AP = 'AP',
  BA = 'BA',
  CE = 'CE',
  DF = 'DF',
  ES = 'ES',
  GO = 'GO',
  MA = 'MA',
  MT = 'MT',
  MS = 'MS',
  MG = 'MG',
  PA = 'PA',
  PB = 'PB',
  PR = 'PR',
  PE = 'PE',
  PI = 'PI',
  RJ = 'RJ',
  RN = 'RN',
  RS = 'RS',
  RO = 'RO',
  RR = 'RR',
  SC = 'SC',
  SE = 'SE',
  SP = 'SP',
  TO = 'TO',
}

export const BrazilianStateFullName: Record<BrazilianState, string> = {
  [BrazilianState.AC]: 'Acre',
  [BrazilianState.AL]: 'Alagoas',
  [BrazilianState.AM]: 'Amazonas',
  [BrazilianState.AP]: 'Amapá',
  [BrazilianState.BA]: 'Bahia',
  [BrazilianState.CE]: 'Ceará',
  [BrazilianState.DF]: 'Distrito Federal',
  [BrazilianState.ES]: 'Espírito Santo',
  [BrazilianState.GO]: 'Goiás',
  [BrazilianState.MA]: 'Maranhão',
  [BrazilianState.MT]: 'Mato Grosso',
  [BrazilianState.MS]: 'Mato Grosso do Sul',
  [BrazilianState.MG]: 'Minas Gerais',
  [BrazilianState.PA]: 'Pará',
  [BrazilianState.PB]: 'Paraíba',
  [BrazilianState.PR]: 'Paraná',
  [BrazilianState.PE]: 'Pernambuco',
  [BrazilianState.PI]: 'Piauí',
  [BrazilianState.RJ]: 'Rio de Janeiro',
  [BrazilianState.RN]: 'Rio Grande do Norte',
  [BrazilianState.RS]: 'Rio Grande do Sul',
  [BrazilianState.RO]: 'Rondônia',
  [BrazilianState.RR]: 'Roraima',
  [BrazilianState.SC]: 'Santa Catarina',
  [BrazilianState.SE]: 'Sergipe',
  [BrazilianState.SP]: 'São Paulo',
  [BrazilianState.TO]: 'Tocantins',
};